// THEME COLORS
import { colors } from "./colors";

export const themeColors = {
  light: {
    text: {
      primaryText: colors.black,
      secondaryText: colors.violet,
      tertiaryText: colors.darkGray,
      subtleText: colors.steelGray,
      accentText: colors.grey,
      semiTransparentText: colors.coolGray,
      mutedText: colors.gray,
      grayText: colors.black,
      inactiveText: colors.inactiveGray,
      actionText: colors.purple,
      disabledText: colors.disabledGray,
      coolGrayText: colors.coolGray,
      lightGrayText: colors.slateGray,
      darkGrayText: colors.darkGray,
      disabledGrayText: colors.gray,
      perlGrayText: colors.inactiveGray,
      silverText: colors.darkSilverText,
      purpleText: colors.deepViolet,
      disableMidGray: colors.midGray,
      success: colors.brightGreen,
      overlayText: colors.overlay,
      inverseText: colors.white,
      red: colors.red,
      themedText: "#821489",
    },
    background: {
      primaryBg: colors.white,
      secondaryBg: colors.offWhite,
      elevatedBg: colors.white,
      overlayBg: colors.white,
      accentBg: colors.pearlPink,
      lightOverlayBg: colors.paleWhite,
      violetBg: colors.violet,
      greenBg: colors.mintGreen,
      redBg: colors.redLight,
      overlay: colors.overlay,
      tabBGTransparent: colors.whiteLightTransparent,
      themedBg: colors.purple,
      avatarBgColor: "#E5BFE7",
      richBlack: colors.white,
      switch: "#821489",
      sheetOverlay: "#fff",
    },
    button: {
      secondaryButton: colors.altLight,
      primaryButton: colors.deepViolet,
      tertiaryButton: "#F6F6F6",
      subtleButton: "#F9F9F9",
      accentButton: colors.white,
      softLavender: "#FEF3FF",
      barBgPrimary: colors.deepViolet,
      barBgSecondary: "#DA94D5",
      barBgThird: "#F6F6F6",
      activeButton: colors.deepPurple,
      disabledButton: "#E3E3E3",
    },
    border: {
      primary: colors.violet,
      secondary: "#EBEBEB",
      tertiary: colors.silver,
      quaternary: "#EEEEEE",
      charcoalGrayBorder: colors.cloudGray,
      sheet: "#8C2F86",
      themedBorder: colors.purple,
      divider: "rgba(0,0,0,0.06)",
    },
    shadow: {
      primary: colors.whiteTrans44,
      purple: "rgba(255, 7, 247, 0.01)",
    },
    utility: {
      danger: colors.red,
    },
    brand: {
      primary: colors.deepViolet,
    },
    state: {
      success: colors.brightGreen,
      error: colors.red,
      warning: colors.orange,
    },
    gradient: {
      primary: ["#C830D2", "#821489"],
      qr: ["#821489", "#821489"],
      qrFrame: [
        "#C4A7F0",
        "#BA9EEE",
        "#AF91EB",
        "#E4D1FF",
        "#BCA0F0",
        "#AE8EE9",
      ],
      border: [
        ["rgba(255, 255, 255, 0)", "rgba(254, 243, 255, 0.5)"],
        ["rgba(58, 7, 61, 0.6)", "rgba(255, 255, 255, 0)"],
      ],
      cardColors: ["#FFFFFF", "#FFFFFF", "#FFFFFF"],
      invitationCard: ["#F6F1FD", "#FBF9FF", "#FEF1FF"],
      feedbackSelected: ["#C830D2", "#821489"],
      feedbackUnselected: ["#FFFFFF", "#FFFFFF"],
      container: ["#F2EFFA", "#FBF1EE", "#FAEBF6", "#FCEBF0"],
      searchBorder: ["#D1A8E0", "#DF56F4", "#C178D1", "#BD00CB"],
      borderB: [" #FFFFFF ", " #E0CEE1", " #E9AAEE"],
    },
  },
  dark: {
    text: {
      primaryText: colors.white,
      secondaryText: colors.white,
      tertiaryText: colors.white,
      subtleText: colors.steelGray,
      accentText: colors.coolGray,
      semiTransparentText: colors.whiteTrans60,
      mutedText: colors.whiteTrans60,
      grayText: colors.gray,
      inactiveText: colors.gray,
      actionText: colors.white,
      disabledText: colors.gray,
      coolGrayText: colors.gray,
      lightGrayText: colors.lightGray,
      darkGrayText: colors.white,
      disabledGrayText: colors.disabledGray,
      perlGrayText: colors.perlGray,
      silverText: colors.silver,
      purpleText: colors.white,
      disableMidGray: colors.disableGray,
      success: colors.green,
      overlayText: colors.white,
      inverseText: colors.black,
      red: colors.red,
      themedText: "#EE07FD",
    },
    background: {
      primaryBg: colors.black,
      secondaryBg: colors.darkBg,
      elevatedBg: colors.charcoal,
      overlayBg: "rgba(255,255,255,0.12)",
      accentBg: colors.deepPurple,
      lightOverlayBg: colors.whiteTrans8Alt,
      violetBg: colors.deepViolet,
      greenBg: colors.forestGreen,
      overlay: "rgba(0, 0, 0, 0.7)",
      tabBGTransparent: colors.blackLightTransparent,
      themedBg: colors.purple,
      avatarBgColor: "#E5BFE7",
      richBlack: colors.richBlack,
      switch: "#EE07FD",
      sheetOverlay: "#232323",
    },
    button: {
      secondaryButton: colors.whiteTrans12Alt,
      primaryButton: colors.deepViolet,
      tertiaryButton: colors.darkCharcoal,
      subtleButton: "#FFFFFF14",
      accentButton: colors.altDark,
      softLavender: "#FFFFFF14",
      barBgPrimary: colors.deepViolet,
      barBgSecondary: "#DA94D5",
      barBgThird: "#FFFFFF14",
      activeButton: colors.purple,
      disabledButton: "rgba(255,255,255,0.12)",
    },
    border: {
      primary: colors.darkPurple,
      secondary: colors.gray,
      tertiary: colors.darkCharcoal,
      quaternary: "#343434",
      charcoalGrayBorder: colors.darkCharcoal,
      sheet: "#8C2F86",
      themedBorder: colors.purple,
      divider: "rgba(255,255,255,0.06)",
    },
    shadow: {
      primary: colors.blackTrans44,
      purple: "rgba(255, 7, 247, 0.01)",
    },
    utility: {
      danger: colors.red,
    },
    brand: {
      primary: colors.deepViolet,
    },
    state: {
      success: colors.green,
      error: colors.red,
      warning: colors.orange,
    },
    gradient: {
      primary: ["#C830D2", "#821489"],
      qr: ["#821489", "#4B0082"],
      qrFrame: [
        "#C4A7F0",
        "#BA9EEE",
        "#AF91EB",
        "#E4D1FF",
        "#BCA0F0",
        "#AE8EE9",
      ],
      border: [
        ["rgba(255, 255, 255, 0)", "rgba(254, 243, 255, 0)"],
        ["rgba(58, 7, 61, 0.6)", "rgba(255, 255, 255, 0)"],
      ],
      cardColors: [
        "rgba(255, 255, 255, 0.04)",
        "rgba(255, 255, 255, 0.12)",
        "rgba(255, 255, 255, 0.04)",
      ],
      invitationCard: ["#9E81C7", "#BDA3EC", "#D467DE"],
      feedbackSelected: ["#C830D2", "#821489"],
      feedbackUnselected: ["#232323", "#232323", "#232323"],
      container: ["#F2EFFA", "#FBF1EE", "#FAEBF6", "#FCEBF0"],
      searchBorder: ["#EEC6FC", "#EF85FF", "#D965F3", "#EE04FF"],
      borderB: ["#242424", "#1D1A1C"],
    },
  },

  golden: {
    text: {
      primaryText: colors.white,
      secondaryText: colors.white,
      tertiaryText: colors.white,
      subtleText: colors.steelGray,
      accentText: colors.coolGray,
      semiTransparentText: colors.whiteTrans60,
      mutedText: colors.whiteTrans60,
      grayText: colors.gray,
      inactiveText: colors.gray,
      actionText: colors.orange,
      disabledText: colors.gray,
      coolGrayText: colors.gray,
      lightGrayText: colors.lightGray,
      darkGrayText: colors.lightGray,
      disabledGrayText: colors.disabledGray,
      perlGrayText: colors.perlGray,
      silverText: colors.silver,
      purpleText: colors.white,
      disableMidGray: colors.disableGray,
      success: colors.green,
      overlayText: colors.white,
      inverseText: colors.black,
      red: colors.red,
      // themedText: colors.gold,
      themedText: "#CBAF4C",
    },
    background: {
      primaryBg: colors.black,
      secondaryBg: colors.darkBg,
      elevatedBg: colors.charcoal,
      overlayBg: colors.whiteTransMain,
      accentBg: colors.deepPurple,
      lightOverlayBg: colors.whiteTrans8Alt,
      violetBg: colors.deepViolet,
      darkerBg: colors.darkerBg,
      overlay: "rgba(0, 0, 0, 0.7)",
      // themedBg: colors.gold,
      themedBg: "#CBAF4C",
      avatarBgColor: "#fbab66ff",
      richBlack: colors.richBlack,
      // switch: '#fa991a',
      switch: "#CBAF4C",
      sheetOverlay: "#232323",
    },
    button: {
      secondaryButton: colors.whiteTrans12Alt,
      primaryButton: colors.orange,
      tertiaryButton: colors.darkCharcoal,
      subtleButton: colors.whiteTrans14,
      accentButton: colors.altDark,
      softLavender: "#FFFFFF14",
      // barBgPrimary: ['#FDE3BB', '#C36510'],
      barBgPrimary: ["#FFFEB3", "#CBAF4C"],
      barBgSecondary: "#F4E5CE",
      barBgThird: "#FFFFFF14",
      activeButton: colors.orange,
      disabledButton: "rgba(255,255,255,0.12)",
    },
    border: {
      primary: colors.orange,
      secondary: colors.gray,
      tertiary: colors.darkCharcoal, //colors.lavenderGray ,
      quaternary: "#343434",
      charcoalGrayBorder: colors.darkCharcoal,
      sheet: colors.orange,
      // themedBorder: colors.gold,
      themedBorder: "#CBAF4C",
      divider: "rgba(255,255,255,0.06)",

      borderGradientColors: [
        ["rgba(255, 255, 255, 0)", "rgba(254, 243, 255, 0)"],
        ["rgba(58, 7, 61, 0.6)", "rgba(255, 255, 255, 0)"],
      ],
    },
    shadow: {
      primary: colors.blackTrans44,
      purple: "rgba(255, 7, 247, 0.01)",
    },
    utility: {
      danger: colors.red,
    },
    brand: {
      // primary: '#FDE3BB',
      primary: "#FFFEB3",
    },
    state: {
      success: colors.green,
      error: colors.red,
      warning: colors.orange,
    },
    gradient: {
      // primary: ['#FDE3BB', '#DC9A4E', '#C36510'],
      primary: ["#FFFEB3", "#AB8E38", "#DEC65E", "#CBAF4C"],
      // qr: ['#FDE3BB', '#DC9A4E', '#C36510'],
      qr: ["#FFFEB3", "#AB8E38", "#DEC65E", "#CBAF4C"],
      // qrFrame: ['#F1E1AC', '#E9CE7B', '#E9CE7B'], // NEW
      qrFrame: ["#FFFEB3", "#AB8E38", "#DEC65E", "#CBAF4C"],
      border: [
        ["rgba(255, 255, 255, 0)", "rgba(254, 243, 255, 0)"],
        ["rgba(58, 7, 61, 0.6)", "rgba(255, 255, 255, 0)"],
      ],
      cardColors: [
        "rgba(51, 51, 51, 0.144)",
        "rgba(255, 255, 255, 0.108)",
        "rgba(51, 51, 51, 0.108)",
      ],
      // invitationCard: ['#FDE3BB', '#DC9A4E', '#C36510'],
      invitationCard: ["#FFFEB3", "#AB8E38", "#DEC65E", "#CBAF4C"],
      // feedbackSelected: ['#FDE3BB', '#DC9A4E', '#C36510'],
      feedbackSelected: ["#FFFEB3", "#AB8E38", "#DEC65E", "#CBAF4C"],
      feedbackUnselected: ["#232323", "#232323", "#232323"],
      // container: ['#FDE3BB', '#DC9A4E', '#C36510'],
      container: ["#FFFEB3", "#AB8E38", "#DEC65E", "#CBAF4C"],
      searchBorder: ["#5D3814", "#925E28", "#8B5119", "#975516"],
      borderB: ["#242424", "#1D1A1C"],
    },
  },

  silver: {
    text: {
      primaryText: colors.white,
      secondaryText: colors.white,
      tertiaryText: colors.white,
      subtleText: colors.steelGray,
      accentText: colors.coolGray,
      semiTransparentText: colors.whiteTrans60,
      mutedText: colors.whiteTrans60,
      grayText: colors.gray,
      inactiveText: colors.gray,
      actionText: colors.white,
      disabledText: colors.gray,
      coolGrayText: colors.gray,
      lightGrayText: colors.lightGray,
      darkGrayText: colors.lightGray,
      disabledGrayText: colors.disabledGray,
      perlGrayText: colors.perlGray,
      silverText: colors.silver,
      purpleText: colors.white,
      disableMidGray: colors.disableGray,
      success: colors.green,
      overlayText: colors.white,
      inverseText: colors.black,
      red: colors.red,
      themedText: colors.silver,
    },
    background: {
      primaryBg: colors.black,
      secondaryBg: colors.darkBg,
      elevatedBg: colors.charcoal,
      overlayBg: colors.whiteTransMain,
      accentBg: colors.deepPurple,
      lightOverlayBg: colors.whiteTrans8Alt,
      violetBg: colors.deepViolet,
      greenBg: colors.forestGreen,
      overlay: "rgba(0, 0, 0, 0.7)",
      themedBg: colors.silver,
      avatarBgColor: "#e6e6e6ff",
      richBlack: colors.richBlack,
      switch: "#757575",
      sheetOverlay: "#232323",
    },
    button: {
      secondaryButton: colors.whiteTrans12Alt,
      primaryButton: colors.silver,
      tertiaryButton: colors.darkCharcoal,
      subtleButton: colors.whiteTrans14,
      accentButton: colors.altDark,
      softLavender: "#FFFFFF14",
      barBgPrimary: ["#FCFCFC", "#A4A4A4", "#575757"],
      barBgSecondary: "#BBBBBB",
      barBgThird: "#FFFFFF14",
      activeButton: colors.lightWhite,
      disabledButton: "rgba(255,255,255,0.12)",
    },
    border: {
      primary: colors.silver,
      secondary: colors.gray,
      tertiary: colors.darkCharcoal, //colors.lavenderGray ,
      quaternary: "#343434",
      charcoalGrayBorder: colors.darkCharcoal,
      sheet: "#BBBBBB",
      themedBorder: colors.silver,
      divider: "rgba(255,255,255,0.06)",

      borderGradientColors: [
        ["rgba(255, 255, 255, 0)", "rgba(254, 243, 255, 0)"],
        ["rgba(58, 7, 61, 0.6)", "rgba(255, 255, 255, 0)"],
      ],
    },
    shadow: {
      primary: colors.blackTrans44,
      purple: "rgba(255, 7, 247, 0.01)",
    },
    utility: {
      danger: colors.red,
    },
    brand: {
      primary: "#FCFCFC",
    },
    state: {
      success: colors.green,
      error: colors.red,
      warning: colors.orange,
    },
    gradient: {
      primary: ["#FCFCFC", "#A4A4A4", "#575757"],
      qr: ["#FCFCFC", "#A4A4A4", "#575757"],
      qrFrame: ["#E0E0E0", "#C1C1C1", "#C1C1C1"], // NEW
      border: [
        ["rgba(255, 255, 255, 0)", "rgba(254, 243, 255, 0)"],
        ["rgba(58, 7, 61, 0.6)", "rgba(255, 255, 255, 0)"],
      ],
      cardColors: [
        "rgba(51, 51, 51, 0.036)",
        "rgba(255, 255, 255, 0.108)",
        "rgba(51, 51, 51, 0.108)",
      ],
      invitationCard: ["#FCFCFC", "#A4A4A4", "#575757"],
      feedbackSelected: ["#FCFCFC", "#A4A4A4", "#575757"],
      feedbackUnselected: ["#232323", "#232323", "#232323"],
      container: ["#FCFCFC", "#A4A4A4", "#575757"],
      searchBorder: ["#646265", "#868686", "#818181", "#9D9D9D"],
      borderB: ["#242424", "#1D1A1C"],
    },
  },
};
